import {
    catTemplate
} from './catTemplate.js';
import {
    dogTemplate
} from './dogTemplate.js';
import {
    birdTemplate
} from './birdTemplate.js';
import {
    fishTemplate
} from './fishTemplate.js';

// https://www.purina.com/cats/cat-breeds

let testCat = new catTemplate({
    id: 201,
    species: 'cat',
    price: 2000,
    gender: 'female',
    weight: 1.6,
    birth_date: '06-28-2019',
    color: 'blue',
    breed: 'Scottish Fold',
    is_sterile: false,
    hair: 'medium',
})
let testDog = new dogTemplate({
    id: 211,
    species: 'dog',
    price: 5000,
    gender: 'male',
    weight: 20,
    birth_date: '05-26-2018',
    color: 'white-gray-black',
    breed: 'Siberian Husky',
    is_sterile: false,
    hair: 'medium',
})
let testBird = new birdTemplate({
    id: 221,
    species: 'bird',
    price: 550,
    gender: 'female',
    weight: 0.5,
    birth_date: '11-15-2018',
    color: 'gray',
    breed: 'African Grey Parrot',
    type: 'singing',
    activity: 'day',
})
let testFish = new fishTemplate({
    id: 231,
    species: 'fish',
    price: 50,
    gender: 'male',
    weight: 0.9,
    birth_date: '08-17-2019',
    color: 'white',
    breed: 'Bass',
    water_type: 'limnetic',
    temper: 'peacefull'
})

console.log(testCat, testDog, testBird, testFish);
////////////////////////////////////////////////////

const animalsList = [
    new catTemplate({
        id: 201,
        species: 'cat',
        price: 2000,
        gender: 'f',
        weight: 1.8,
        birthDate: '28-6-2019',
        size: 'small',
        note: '-',
        breed: 'Scottish Fold',
        sterile: false,
        hair: 'Blue'
    }),
    new catTemplate({
        species: 'cat',
        price: 1845,
        gender: 'm',
        weight: 2,
        birthDate: '10-6-2017',
        size: 'Small',
        note: '-',
        breed: 'American Curl',
        sterile: false,
        hair: 'Black&White'
    }),
    new catTemplate({
        species: 'cat',
        price: 1842,
        gender: 'f',
        weight: 2.3,
        birthDate: '19-9-2018',
        size: 'Small',
        note: '-',
        breed: 'American Curl',
        sterile: false,
        hair: 'Chocolate'
    }),
    new catTemplate({
        species: 'cat',
        price: 1847,
        gender: 'm',
        weight: 1.5,
        birthDate: '11-8-2018',
        size: 'Small',
        note: '-',
        breed: 'Singapura Cat',
        sterile: false,
        hair: 'Sepia'
    }),
    new catTemplate({
        species: 'cat',
        price: 1849,
        gender: 'm',
        weight: 1.7,
        birthDate: '11-8-2018',
        size: 'Small',
        note: '-',
        breed: 'Singapura Cat',
        sterile: false,
        hair: 'Sepia'
    }),
    new catTemplate({
        species: 'cat',
        price: 1851,
        gender: 'f',
        weight: 1.9,
        birthDate: '17-7-2019',
        size: 'Small',
        note: '-',
        breed: 'Oriental',
        sterile: true,
        hair: 'Ebony'
    }),
    new catTemplate({
        species: 'cat',
        price: 1952,
        gender: 'f',
        weight: 1.2,
        birthDate: '1-2-2019',
        size: 'Small',
        note: '-',
        breed: 'Devon Rex',
        sterile: true,
        hair: 'White'
    }),
    new catTemplate({
        species: 'cat',
        price: 2000,
        gender: 'f',
        weight: 3.6,
        birthDate: '3-3-2018',
        size: 'Medium',
        note: '-',
        breed: 'Chartreux',
        sterile: false,
        hair: 'Blue'
    }),
    new catTemplate({
        species: 'cat',
        price: 1990,
        gender: 'm',
        weight: 4.3,
        birthDate: '21-4-2018',
        size: 'Large',
        note: '-',
        breed: 'Ragamuffin',
        sterile: true,
        hair: 'Cream'
    }),
    new catTemplate({
        species: 'cat',
        price: 1985,
        gender: 'f',
        weight: 4.6,
        birthDate: '13-4-2018',
        size: 'Large',
        note: '-',
        breed: 'Persian',
        sterile: true,
        hair: 'Lilac'
    }),
    ///////////////////////////////
    new dogTemplate({
        species: 'dog',
        price: 3500,
        gender: 'm',
        weight: 10,
        birthDate: '8-8-2016',
        size: 'Small',
        note: '-',
        breed: 'Beagle',
        sterile: false,
        hair: 'Tri-color (black, tan and white)',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3300,
        gender: 'f',
        weight: 8,
        birthDate: '18-8-2019',
        size: 'Small',
        note: '-',
        breed: 'French Bulldog',
        sterile: false,
        hair: 'Black',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3600,
        gender: 'm',
        weight: 7,
        birthDate: '4-4-2018',
        size: 'Small',
        note: '-',
        breed: 'Pug',
        sterile: false,
        hair: 'Cream',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3560,
        gender: 'm',
        weight: 11,
        birthDate: '14-6-2018',
        size: 'Medium',
        note: '-',
        breed: 'American Eskimo',
        sterile: false,
        hair: 'White',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3360,
        gender: 'f',
        weight: 9,
        birthDate: '14-6-2018',
        size: 'Medium',
        note: '-',
        breed: 'Basset Hound',
        sterile: false,
        hair: 'Tri-color (black, brown and white)',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3420,
        gender: 'm',
        weight: 15,
        birthDate: '3-11-2018',
        size: 'Large',
        note: '-',
        breed: 'Black Russian Terrier',
        sterile: false,
        hair: 'Black',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3620,
        gender: 'f',
        weight: 14,
        birthDate: '13-10-2018',
        size: 'Large',
        note: '-',
        breed: 'Bloodhound',
        sterile: false,
        hair: 'Black and tan',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3210,
        gender: 'f',
        weight: 10,
        birthDate: '7-5-2017',
        size: 'Medium',
        note: '-',
        breed: 'Border Collie',
        sterile: false,
        hair: 'Black and white',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3480,
        gender: 'm',
        weight: 7,
        birthDate: '17-4-2019',
        size: 'Small',
        note: '-',
        breed: 'Boston Terrier',
        sterile: false,
        hair: 'Black and white',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3190,
        gender: 'f',
        weight: 17,
        birthDate: '13-6-2016',
        size: 'Giant',
        note: '-',
        breed: 'Bullmastiff',
        sterile: false,
        hair: 'Fawn',
        croppedEars: false
    }),
    new dogTemplate({
        species: 'dog',
        price: 3550,
        gender: 'f',
        weight: 14,
        birthDate: '14-6-2017',
        size: 'Large',
        note: '-',
        breed: 'Cane Corso',
        sterile: false,
        hair: 'Black',
        croppedEars: false
    }),
    new birdTemplate({
        species: 'bird',
        price: 800,
        gender: 'm',
        weight: 1,
        birthDate: '6-7-2018',
        size: 'small',
        note: '-',
        breed: 'African Gray Parrot',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 830,
        gender: 'f',
        weight: 1.5,
        birthDate: '1-7-2018',
        size: 'small',
        note: '-',
        breed: 'African Gray Parrot',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 820,
        gender: 'm',
        weight: 1.2,
        birthDate: '9-7-2018',
        size: 'small',
        note: '-',
        breed: 'African Gray Parrot',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 880,
        gender: 'm',
        weight: 2,
        birthDate: '19-7-2018',
        size: 'small',
        note: '-',
        breed: 'African Gray Parrot',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 910,
        gender: 'f',
        weight: 1.1,
        birthDate: '2-7-2019',
        size: 'small',
        note: '-',
        breed: 'Amazon Parrots',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 940,
        gender: 'f',
        weight: 2,
        birthDate: '19-2-2018',
        size: 'medium',
        note: '-',
        breed: 'Amazon Parrots',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 1000,
        gender: 'f',
        weight: 2,
        birthDate: '16-3-2018',
        size: 'small',
        note: '-',
        breed: 'Black-throated Sparrow',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 930,
        gender: 'f',
        weight: 1.7,
        birthDate: '14-2-2018',
        size: 'small',
        note: '-',
        breed: 'Black-throated Sparrow',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 915,
        gender: 'f',
        weight: 1.1,
        birthDate: '6-7-2018',
        size: 'small',
        note: '-',
        breed: 'Black-throated Sparrow',
        type: 'singing',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 950,
        gender: 'm',
        weight: 4,
        birthDate: '14-2-2018',
        size: 'medium',
        note: '-',
        breed: 'Wandering Albatross',
        type: 'waterfowl',
        activity: 'day',
    }),
    new birdTemplate({
        species: 'bird',
        price: 790,
        gender: 'f',
        weight: 3.5,
        birthDate: '16-3-2018',
        size: 'medium',
        note: '-',
        breed: 'Wandering Albatross',
        type: 'waterfowl',
        activity: 'day',
    }),
    new fishTemplate({
        species: 'fish',
        price: 150,
        gender: 'm',
        weight: 1,
        birthDate: '11-5-2019',
        size: 'small',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 80,
    }),
    new fishTemplate({
        species: 'fish',
        price: 155,
        gender: 'f',
        weight: 1,
        birthDate: '11-5-2019',
        size: 'small',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 70,
    }),
    new fishTemplate({
        species: 'fish',
        price: 140,
        gender: 'm',
        weight: 1,
        birthDate: '12-5-2019',
        size: 'small',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 60,
    }),
    new fishTemplate({
        species: 'fish',
        price: 120,
        gender: 'm',
        weight: 1.1,
        birthDate: '16-5-2019',
        size: 'medium',
        note: '-',
        type: 'brackish',
        predatory: true,
        maxSize: 100,
    }),
    new fishTemplate({
        species: 'fish',
        price: 170,
        gender: 'f',
        weight: 1,
        birthDate: '19-2-2019',
        size: 'small',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 75,
    }),
    new fishTemplate({
        species: 'fish',
        price: 120,
        gender: 'm',
        weight: 1,
        birthDate: '11-5-2019',
        size: 'medium',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 74,
    }),
    new fishTemplate({
        species: 'fish',
        price: 120,
        gender: 'f',
        weight: 1,
        birthDate: '12-2-2019',
        size: 'small',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 60,
    }),
    new fishTemplate({
        species: 'fish',
        price: 170,
        gender: 'm',
        weight: 1,
        birthDate: '15-5-2019',
        size: 'medium',
        note: '-',
        type: 'limnetic',
        predatory: false,
        maxSize: 30,
    }),
    new fishTemplate({
        species: 'fish',
        price: 135,
        gender: 'm',
        weight: 1,
        birthDate: '11-4-2019',
        size: 'small',
        note: '-',
        type: 'brackish',
        predatory: false,
        maxSize: 40,
    }),
    new fishTemplate({
        species: 'fish',
        price: 186,
        gender: 'f',
        weight: 1,
        birthDate: '12-1-2019',
        size: 'medium',
        note: '-',
        type: 'brackish',
        predatory: false,
        maxSize: 30,
    }),

]

// console.log(JSON.stringify(animalsList));